# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file '../guiPages/downloadPopUp.ui'
#
# Created by: PyQt5 UI code generator 5.15.7
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_downloadPopUp(object):
    def setupUi(self, downloadPopUp):
        downloadPopUp.setObjectName("downloadPopUp")
        downloadPopUp.resize(400, 250)
        downloadPopUp.setStyleSheet("background-color: rgb(196, 236, 236);")
        self.downloadPopUp_2 = QtWidgets.QFrame(downloadPopUp)
        self.downloadPopUp_2.setGeometry(QtCore.QRect(0, 0, 400, 250))
        self.downloadPopUp_2.setMaximumSize(QtCore.QSize(500, 600))
        self.downloadPopUp_2.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.downloadPopUp_2.setFrameShadow(QtWidgets.QFrame.Raised)
        self.downloadPopUp_2.setObjectName("downloadPopUp_2")
        self.logoButton = QtWidgets.QPushButton(self.downloadPopUp_2)
        self.logoButton.setGeometry(QtCore.QRect(165, 40, 70, 70))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setUnderline(False)
        self.logoButton.setFont(font)
        self.logoButton.setStyleSheet("background-color: rgb(244, 249, 250);\n"
"border: none;\n"
"color: black;")
        self.logoButton.setText("")
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap("../guiPages/../images/icon_blueBackground.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.logoButton.setIcon(icon)
        self.logoButton.setIconSize(QtCore.QSize(90, 90))
        self.logoButton.setObjectName("logoButton")
        self.frame = QtWidgets.QFrame(self.downloadPopUp_2)
        self.frame.setGeometry(QtCore.QRect(0, 119, 400, 60))
        self.frame.setStyleSheet("border: none;")
        self.frame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame.setObjectName("frame")
        self.label = QtWidgets.QLabel(self.frame)
        self.label.setGeometry(QtCore.QRect(40, 15, 320, 30))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(20)
        font.setBold(True)
        font.setItalic(False)
        self.label.setFont(font)
        self.label.setStyleSheet("font: 700 20pt \"Arial\";")
        self.label.setAlignment(QtCore.Qt.AlignCenter)
        self.label.setObjectName("label")
        self.pushButton = QtWidgets.QPushButton(self.downloadPopUp_2)
        self.pushButton.setGeometry(QtCore.QRect(150, 190, 100, 30))
        self.pushButton.setStyleSheet("background-color: rgb(77, 206, 175);\n"
"font: 18pt \"Arial\";\n"
"border: none;")
        self.pushButton.setObjectName("pushButton")

        self.retranslateUi(downloadPopUp)
        QtCore.QMetaObject.connectSlotsByName(downloadPopUp)

    def retranslateUi(self, downloadPopUp):
        _translate = QtCore.QCoreApplication.translate
        downloadPopUp.setWindowTitle(_translate("downloadPopUp", "Form"))
        self.label.setText(_translate("downloadPopUp", "Download Completed"))
        self.pushButton.setText(_translate("downloadPopUp", "Finish"))

    def pushButtonClicked(self, downloadPopUp):
        downloadPopUp.close()

if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    downloadPopUp = QtWidgets.QWidget()
    ui = Ui_downloadPopUp()
    ui.setupUi(downloadPopUp)
    downloadPopUp.show()
    sys.exit(app.exec_())
