# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file '../guiPages/endingwindow.ui'
#
# Created by: PyQt5 UI code generator 5.15.7
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_EndingWindow(object):
    def setupUi(self, EndingWindow):
        EndingWindow.setObjectName("EndingWindow")
        EndingWindow.resize(600, 400)
        EndingWindow.setStyleSheet("background-color: rgb(244, 249, 250);")
        self.EndingWindow_frame = QtWidgets.QFrame(EndingWindow)
        self.EndingWindow_frame.setGeometry(QtCore.QRect(0, 0, 800, 600))
        self.EndingWindow_frame.setStyleSheet("background-color: rgb(244, 249, 250);")
        self.EndingWindow_frame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.EndingWindow_frame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.EndingWindow_frame.setObjectName("EndingWindow_frame")
        self.label = QtWidgets.QLabel(self.EndingWindow_frame)
        self.label.setGeometry(QtCore.QRect(90, 30, 400, 50))
        self.label.setStyleSheet("font: 14pt \"Segoe UI\";")
        self.label.setAlignment(QtCore.Qt.AlignCenter)
        self.label.setObjectName("label")
        self.download = QtWidgets.QLabel(self.EndingWindow_frame)
        self.download.setGeometry(QtCore.QRect(230, 80, 100, 20))
        self.download.setStyleSheet("color: rgb(17, 46, 63);\n"
"text-decoration: underline;\n"
"font: 12pt \"Segoe UI\";")
        self.download.setAlignment(QtCore.Qt.AlignCenter)
        self.download.setObjectName("download")
        self.sendtoemail = QtWidgets.QLabel(self.EndingWindow_frame)
        self.sendtoemail.setGeometry(QtCore.QRect(210, 110, 150, 20))
        self.sendtoemail.setStyleSheet("font: 12pt \"Segoe UI\";\n"
"color: rgb(17, 46, 58);\n"
"text-decoration: underline;")
        self.sendtoemail.setAlignment(QtCore.Qt.AlignCenter)
        self.sendtoemail.setObjectName("sendtoemail")
        self.thanks = QtWidgets.QTextEdit(self.EndingWindow_frame)
        self.thanks.setGeometry(QtCore.QRect(80, 140, 401, 131))
        self.thanks.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.thanks.setObjectName("thanks")
        self.feedback = QtWidgets.QLabel(self.EndingWindow_frame)
        self.feedback.setGeometry(QtCore.QRect(150, 240, 281, 50))
        self.feedback.setStyleSheet("font: 12pt \"Segoe UI\";")
        self.feedback.setAlignment(QtCore.Qt.AlignCenter)
        self.feedback.setObjectName("feedback")

        self.retranslateUi(EndingWindow)
        QtCore.QMetaObject.connectSlotsByName(EndingWindow)

    def retranslateUi(self, EndingWindow):
        _translate = QtCore.QCoreApplication.translate
        EndingWindow.setWindowTitle(_translate("EndingWindow", "Form"))
        self.label.setText(_translate("EndingWindow", "Your music sheet is ready!"))
        self.download.setText(_translate("EndingWindow", "Download"))
        self.sendtoemail.setText(_translate("EndingWindow", "Send to email"))
        self.thanks.setHtml(_translate("EndingWindow", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><meta charset=\"utf-8\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"hr { height: 1px; border-width: 0; }\n"
"li.unchecked::marker { content: \"\\2610\"; }\n"
"li.checked::marker { content: \"\\2612\"; }\n"
"</style></head><body style=\" font-family:\'Segoe UI\'; font-size:9pt; font-weight:400; font-style:normal;\">\n"
"<p align=\"center\" style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-size:28pt; font-weight:700;\">Thank you for using<br /> Perfect</span><span style=\" font-size:28pt; font-weight:700; color:#2774a7;\">Pitch</span><span style=\" font-size:28pt; font-weight:700;\">!</span></p></body></html>"))
        self.feedback.setText(_translate("EndingWindow", "We appreciate your feedback:"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    EndingWindow = QtWidgets.QWidget()
    ui = Ui_EndingWindow()
    ui.setupUi(EndingWindow)
    EndingWindow.show()
    sys.exit(app.exec_())
