# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file '../guiPages/initPage.ui'
#
# Created by: PyQt5 UI code generator 5.15.7
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets
import settingsPopUpController
import aboutPerfectPitchController
import sys
import main

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        # Main Window
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(800, 600)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")

        # Start Button
        self.startButton = QtWidgets.QPushButton(self.centralwidget)
        self.startButton.setGeometry(QtCore.QRect(300, 400, 191, 51))
        self.startButton.setObjectName("startButton")

        # About Button
        self.abouButton = QtWidgets.QPushButton(self.centralwidget)
        self.abouButton.setGeometry(QtCore.QRect(650, 500, 150, 30))
        self.abouButton.setObjectName("abouButton")
 
        # Background Image
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 800, 22))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)

        # Status Bar
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        # Set up the window
        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

        # Actions
        self.startButton.clicked.connect(self.pressInitButton)
        self.abouButton.clicked.connect(self.pressAboutButton)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        self.startButton.setText(_translate("MainWindow", "PushButton"))
        self.abouButton.setText(_translate("MainWindow", "About Perfect Pitch"))

        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))

    # Opens the settings pop up window
    def pressInitButton(self):
        self.SettingsPopUpWindow = QtWidgets.QMainWindow()
        window = settingsPopUpController.Ui_SettingsPopUp()
        window.setupUi(self.SettingsPopUpWindow)
        self.SettingsPopUpWindow.show()
        print(self.userName)

    # Opens the about Perfect Pitch pop up window
    def pressAboutButton(self):
        self.AboutPopUpWindow = QtWidgets.QMainWindow()
        window = aboutPerfectPitchController.Ui_aboutPerfectPitch()
        window.setupUi(self.AboutPopUpWindow)
        self.AboutPopUpWindow.show()