# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file '../guiPages/mainWindowNotRecording.ui'
#
# Created by: PyQt5 UI code generator 5.15.7
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_mainWindow(object):
    def setupUi(self, mainWindow):
        mainWindow.setObjectName("mainWindow")
        mainWindow.resize(600, 400)
        mainWindow.setStyleSheet("background-color: rgb(244, 249, 250);")
        self.centralwidget = QtWidgets.QWidget(mainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.initialwindow_frame = QtWidgets.QFrame(self.centralwidget)
        self.initialwindow_frame.setGeometry(QtCore.QRect(0, 0, 600, 400))
        self.initialwindow_frame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.initialwindow_frame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.initialwindow_frame.setObjectName("initialwindow_frame")
        self.logo = QtWidgets.QLabel(self.initialwindow_frame)
        self.logo.setGeometry(QtCore.QRect(490, 10, 70, 70))
        self.logo.setText("")
        self.logo.setPixmap(QtGui.QPixmap("../guiPages/../images/icon_whiteBackground.png"))
        self.logo.setScaledContents(True)
        self.logo.setObjectName("logo")
        self.defenitionsButton = QtWidgets.QPushButton(self.initialwindow_frame, clicked=lambda: self.defenitionsButtonClicked())
        self.defenitionsButton.setGeometry(QtCore.QRect(20, 10, 41, 41))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setUnderline(False)
        self.defenitionsButton.setFont(font)
        self.defenitionsButton.setStyleSheet("background-color: rgb(244, 249, 250);\n"
"border: none;\n"
"color: black;")
        self.defenitionsButton.setText("")
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap("../guiPages/../images/defenitionsLogo.jpg"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.defenitionsButton.setIcon(icon)
        self.defenitionsButton.setObjectName("defenitionsButton")
        self.label = QtWidgets.QLabel(self.initialwindow_frame)
        self.label.setGeometry(QtCore.QRect(250, 160, 100, 16))
        self.label.setStyleSheet("color: rgb(0, 0, 0);\n"
"font: 13pt \"Arial\";")
        self.label.setAlignment(QtCore.Qt.AlignCenter)
        self.label.setObjectName("label")
        self.line4 = QtWidgets.QFrame(self.initialwindow_frame)
        self.line4.setGeometry(QtCore.QRect(50, 300, 500, 3))
        self.line4.setFrameShape(QtWidgets.QFrame.HLine)
        self.line4.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line4.setObjectName("line4")
        self.line3 = QtWidgets.QFrame(self.initialwindow_frame)
        self.line3.setGeometry(QtCore.QRect(50, 320, 500, 3))
        self.line3.setFrameShape(QtWidgets.QFrame.HLine)
        self.line3.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line3.setObjectName("line3")
        self.line2 = QtWidgets.QFrame(self.initialwindow_frame)
        self.line2.setGeometry(QtCore.QRect(50, 340, 500, 3))
        self.line2.setFrameShape(QtWidgets.QFrame.HLine)
        self.line2.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line2.setObjectName("line2")
        self.line1 = QtWidgets.QFrame(self.initialwindow_frame)
        self.line1.setGeometry(QtCore.QRect(50, 360, 500, 3))
        self.line1.setFrameShape(QtWidgets.QFrame.HLine)
        self.line1.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line1.setObjectName("line1")
        self.line5 = QtWidgets.QFrame(self.initialwindow_frame)
        self.line5.setGeometry(QtCore.QRect(50, 280, 500, 3))
        self.line5.setFrameShape(QtWidgets.QFrame.HLine)
        self.line5.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line5.setObjectName("line5")
        self.label_2 = QtWidgets.QLabel(self.initialwindow_frame)
        self.label_2.setGeometry(QtCore.QRect(275, 90, 50, 50))
        self.label_2.setText("")
        self.label_2.setPixmap(QtGui.QPixmap("../guiPages/../images/microphoneOn.png"))
        self.label_2.setScaledContents(True)
        self.label_2.setObjectName("label_2")
        mainWindow.setCentralWidget(self.centralwidget)

        self.retranslateUi(mainWindow)
        QtCore.QMetaObject.connectSlotsByName(mainWindow)

    def retranslateUi(self, mainWindow):
        _translate = QtCore.QCoreApplication.translate
        mainWindow.setWindowTitle(_translate("mainWindow", "MainWindow"))
        self.label.setText(_translate("mainWindow", "Not recording"))

    def defenitionsButtonClicked(self):
        from settingsPopUpcontroller import Ui_SettingsPopUp

        self.settingsPopUp = QtWidgets.QMainWindow()
        self.ui = Ui_SettingsPopUp()
        self.ui.setupUi(self.settingsPopUp)
        self.settingsPopUp.show()

if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    mainWindow = QtWidgets.QMainWindow()
    ui = Ui_mainWindow()
    ui.setupUi(mainWindow)
    mainWindow.show()
    sys.exit(app.exec_())
