# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file '../guiPages/SettingsPopUp.ui'
#
# Created by: PyQt5 UI code generator 5.15.7
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_SettingsPopUp(object):
    def setupUi(self, SettingsPopUp):
        SettingsPopUp.setObjectName("SettingsPopUp")
        SettingsPopUp.resize(360, 340)
        SettingsPopUp.setMinimumSize(QtCore.QSize(0, 0))
        SettingsPopUp.setMaximumSize(QtCore.QSize(500, 600))
        SettingsPopUp.setStyleSheet("background-color: rgb(196, 236, 236);")
        self.settings_frame = QtWidgets.QFrame(SettingsPopUp)
        self.settings_frame.setGeometry(QtCore.QRect(0, 0, 360, 340))
        self.settings_frame.setMaximumSize(QtCore.QSize(500, 600))
        self.settings_frame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.settings_frame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.settings_frame.setObjectName("settings_frame")
        self.settings = QtWidgets.QTextEdit(self.settings_frame)
        self.settings.setGeometry(QtCore.QRect(10, 10, 140, 40))
        self.settings.setMouseTracking(True)
        self.settings.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.settings.setVerticalScrollBarPolicy(QtCore.Qt.ScrollBarAsNeeded)
        self.settings.setObjectName("settings")
        self.f0 = QtWidgets.QTextEdit(self.settings_frame)
        self.f0.setGeometry(QtCore.QRect(10, 60, 150, 30))
        self.f0.setAutoFillBackground(False)
        self.f0.setStyleSheet("background-color: rgb(7, 73, 91);")
        self.f0.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.f0.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.f0.setObjectName("f0")
        self.processing_window = QtWidgets.QTextEdit(self.settings_frame)
        self.processing_window.setGeometry(QtCore.QRect(10, 120, 150, 30))
        self.processing_window.setAutoFillBackground(False)
        self.processing_window.setStyleSheet("background-color: rgb(7, 73, 91);")
        self.processing_window.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.processing_window.setObjectName("processing_window")
        self.minfreq = QtWidgets.QTextEdit(self.settings_frame)
        self.minfreq.setGeometry(QtCore.QRect(10, 180, 150, 30))
        self.minfreq.setAutoFillBackground(False)
        self.minfreq.setStyleSheet("background-color: rgb(7, 73, 91);")
        self.minfreq.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.minfreq.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.minfreq.setObjectName("minfreq")
        self.maxfreq = QtWidgets.QTextEdit(self.settings_frame)
        self.maxfreq.setGeometry(QtCore.QRect(10, 240, 150, 30))
        self.maxfreq.setAutoFillBackground(False)
        self.maxfreq.setStyleSheet("background-color: rgb(7, 73, 91);")
        self.maxfreq.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.maxfreq.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.maxfreq.setObjectName("maxfreq")
        self.f0_input = QtWidgets.QTextEdit(self.settings_frame)
        self.f0_input.setGeometry(QtCore.QRect(200, 60, 150, 30))
        self.f0_input.setAutoFillBackground(False)
        self.f0_input.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.f0_input.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.f0_input.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.f0_input.setObjectName("f0_input")
        self.processing_window_input = QtWidgets.QTextEdit(self.settings_frame)
        self.processing_window_input.setGeometry(QtCore.QRect(200, 120, 150, 30))
        self.processing_window_input.setAutoFillBackground(False)
        self.processing_window_input.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.processing_window_input.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.processing_window_input.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.processing_window_input.setObjectName("processing_window_input")
        self.minfreq_slider = QtWidgets.QSlider(self.settings_frame)
        self.minfreq_slider.setGeometry(QtCore.QRect(200, 180, 150, 30))
        self.minfreq_slider.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.minfreq_slider.setOrientation(QtCore.Qt.Horizontal)
        self.minfreq_slider.setObjectName("minfreq_slider")
        self.maxfreq_slider = QtWidgets.QSlider(self.settings_frame)
        self.maxfreq_slider.setGeometry(QtCore.QRect(200, 240, 150, 30))
        self.maxfreq_slider.setOrientation(QtCore.Qt.Horizontal)
        self.maxfreq_slider.setObjectName("maxfreq_slider")
        self.saveButton = QtWidgets.QPushButton(self.settings_frame)
        self.saveButton.setGeometry(QtCore.QRect(35, 290, 100, 32))
        self.saveButton.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.saveButton.setObjectName("saveButton")
        self.cancelButton = QtWidgets.QPushButton(self.settings_frame)
        self.cancelButton.setGeometry(QtCore.QRect(220, 290, 100, 32))
        self.cancelButton.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.cancelButton.setObjectName("cancelButton")

        self.retranslateUi(SettingsPopUp)
        QtCore.QMetaObject.connectSlotsByName(SettingsPopUp)

    def retranslateUi(self, SettingsPopUp):
        _translate = QtCore.QCoreApplication.translate

        SettingsPopUp.setWindowTitle(_translate("SettingsPopUp", "SettingsPopUp"))
        self.settings.setHtml(_translate("SettingsPopUp", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><meta charset=\"utf-8\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"hr { height: 1px; border-width: 0; }\n"
"li.unchecked::marker { content: \"\\2610\"; }\n"
"li.checked::marker { content: \"\\2612\"; }\n"
"</style></head><body style=\" font-family:\'.AppleSystemUIFont\'; font-size:13pt; font-weight:400; font-style:normal;\">\n"
"<p style=\" margin-top:12px; margin-bottom:12px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-family:\'Segoe UI\'; font-size:14pt; font-weight:700; color:#ffffff;\">Settings</span></p></body></html>"))
        self.f0.setHtml(_translate("SettingsPopUp", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><meta charset=\"utf-8\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"hr { height: 1px; border-width: 0; }\n"
"li.unchecked::marker { content: \"\\2610\"; }\n"
"li.checked::marker { content: \"\\2612\"; }\n"
"</style></head><body style=\" font-family:\'.AppleSystemUIFont\'; font-size:13pt; font-weight:400; font-style:normal;\">\n"
"<p align=\"center\" style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-family:\'Segoe UI\'; font-size:10pt; color:#ffffff;\">Fundamental frequency</span></p></body></html>"))
        self.processing_window.setHtml(_translate("SettingsPopUp", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><meta charset=\"utf-8\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"hr { height: 1px; border-width: 0; }\n"
"li.unchecked::marker { content: \"\\2610\"; }\n"
"li.checked::marker { content: \"\\2612\"; }\n"
"</style></head><body style=\" font-family:\'.AppleSystemUIFont\'; font-size:13pt; font-weight:400; font-style:normal;\">\n"
"<p align=\"center\" style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-family:\'Segoe UI\'; font-size:10pt; color:#ffffff;\">Processing window</span></p></body></html>"))
        self.minfreq.setHtml(_translate("SettingsPopUp", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><meta charset=\"utf-8\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"hr { height: 1px; border-width: 0; }\n"
"li.unchecked::marker { content: \"\\2610\"; }\n"
"li.checked::marker { content: \"\\2612\"; }\n"
"</style></head><body style=\" font-family:\'.AppleSystemUIFont\'; font-size:13pt; font-weight:400; font-style:normal;\">\n"
"<p align=\"center\" style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-family:\'Segoe UI\'; font-size:10pt; color:#ffffff;\">Minimum frequency</span></p></body></html>"))
        self.maxfreq.setHtml(_translate("SettingsPopUp", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><meta charset=\"utf-8\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"hr { height: 1px; border-width: 0; }\n"
"li.unchecked::marker { content: \"\\2610\"; }\n"
"li.checked::marker { content: \"\\2612\"; }\n"
"</style></head><body style=\" font-family:\'.AppleSystemUIFont\'; font-size:13pt; font-weight:400; font-style:normal;\">\n"
"<p align=\"center\" style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-family:\'Segoe UI\'; font-size:10pt; color:#ffffff;\">Maximum frequency</span></p></body></html>"))
        self.f0_input.setHtml(_translate("SettingsPopUp", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><meta charset=\"utf-8\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"hr { height: 1px; border-width: 0; }\n"
"li.unchecked::marker { content: \"\\2610\"; }\n"
"li.checked::marker { content: \"\\2612\"; }\n"
"</style></head><body style=\" font-family:\'.AppleSystemUIFont\'; font-size:13pt; font-weight:400; font-style:normal;\">\n"
"<p align=\"center\" style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-family:\'Segoe UI\'; font-size:10pt; color:#000000;\">44000Hz</span></p></body></html>"))
        self.processing_window_input.setHtml(_translate("SettingsPopUp", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><meta charset=\"utf-8\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"hr { height: 1px; border-width: 0; }\n"
"li.unchecked::marker { content: \"\\2610\"; }\n"
"li.checked::marker { content: \"\\2612\"; }\n"
"</style></head><body style=\" font-family:\'.AppleSystemUIFont\'; font-size:13pt; font-weight:400; font-style:normal;\">\n"
"<p align=\"center\" style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-family:\'Segoe UI\'; font-size:9pt;\">1sec</span></p></body></html>"))
        self.saveButton.setText(_translate("SettingsPopUp", "Save"))
        self.cancelButton.setText(_translate("SettingsPopUp", "Cancel"))

# Actions
        #self.saveButton.clicked.connect(self.pressSaveButton)
        #self.cancelButton.clicked.connect(self.pressCancelButton)



# Delete main
if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    SettingsPopUp = QtWidgets.QWidget()
    ui = Ui_SettingsPopUp()
    ui.setupUi(SettingsPopUp)
    SettingsPopUp.show()
    sys.exit(app.exec_())
