# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'guiPages/mainWindow.ui'
#
# Created by: PyQt5 UI code generator 5.15.7
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets
 

class Ui_mainWindow(object):
    def setupUi(self, mainWindow):
        mainWindow.setObjectName("mainWindow")
        mainWindow.resize(600, 400)
        mainWindow.setStyleSheet("background-color: rgb(244, 249, 250);")
        self.centralwidget = QtWidgets.QWidget(mainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.mainWindowFrame = QtWidgets.QFrame(self.centralwidget)
        self.mainWindowFrame.setGeometry(QtCore.QRect(0, 0, 600, 400))
        self.mainWindowFrame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.mainWindowFrame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.mainWindowFrame.setObjectName("mainWindowFrame")
        self.defenitionsButton = QtWidgets.QPushButton(self.mainWindowFrame)
        self.defenitionsButton.setGeometry(QtCore.QRect(10, 10, 70, 70))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setUnderline(False)
        self.defenitionsButton.setFont(font)
        self.defenitionsButton.setStyleSheet("background-color: rgb(244, 249, 250);\n"
"border: none;\n"
"color: black;")
        self.defenitionsButton.setText("")
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap("guiPages/../images/defenitionsLogo.jpg"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.defenitionsButton.setIcon(icon)
        self.defenitionsButton.setIconSize(QtCore.QSize(25, 25))
        self.defenitionsButton.setObjectName("defenitionsButton")
        self.recordingLabel = QtWidgets.QLabel(self.mainWindowFrame)
        self.recordingLabel.setGeometry(QtCore.QRect(250, 150, 100, 16))
        self.recordingLabel.setStyleSheet("color: rgb(0, 0, 0);\n"
"font: 13pt \"Arial\";")
        self.recordingLabel.setAlignment(QtCore.Qt.AlignCenter)
        self.recordingLabel.setObjectName("recordingLabel")
        self.line4 = QtWidgets.QFrame(self.mainWindowFrame)
        self.line4.setGeometry(QtCore.QRect(50, 264, 500, 1))
        self.line4.setStyleSheet("border-color: black;\n"
"background-color: black;\n"
"")
        self.line4.setFrameShadow(QtWidgets.QFrame.Plain)
        self.line4.setFrameShape(QtWidgets.QFrame.HLine)
        self.line4.setObjectName("line4")
        self.line3 = QtWidgets.QFrame(self.mainWindowFrame)
        self.line3.setGeometry(QtCore.QRect(50, 278, 500, 1))
        self.line3.setStyleSheet("border-color: black;\n"
"background-color: black;")
        self.line3.setFrameShadow(QtWidgets.QFrame.Plain)
        self.line3.setFrameShape(QtWidgets.QFrame.HLine)
        self.line3.setObjectName("line3")
        self.line2 = QtWidgets.QFrame(self.mainWindowFrame)
        self.line2.setGeometry(QtCore.QRect(50, 292, 500, 1))
        self.line2.setStyleSheet("border-color: black;\n"
"background-color: black;")
        self.line2.setFrameShadow(QtWidgets.QFrame.Plain)
        self.line2.setFrameShape(QtWidgets.QFrame.HLine)
        self.line2.setObjectName("line2")
        self.line1 = QtWidgets.QFrame(self.mainWindowFrame)
        self.line1.setGeometry(QtCore.QRect(50, 306, 500, 1))
        self.line1.setStyleSheet("border-color: black;\n"
"background-color: black;")
        self.line1.setFrameShadow(QtWidgets.QFrame.Plain)
        self.line1.setFrameShape(QtWidgets.QFrame.HLine)
        self.line1.setObjectName("line1")
        self.line5 = QtWidgets.QFrame(self.mainWindowFrame)
        self.line5.setGeometry(QtCore.QRect(50, 250, 500, 1))
        self.line5.setStyleSheet("border-color: black;\n"
"background-color: black;")
        self.line5.setFrameShadow(QtWidgets.QFrame.Plain)
        self.line5.setFrameShape(QtWidgets.QFrame.HLine)
        self.line5.setObjectName("line5")
        self.microphoneButton = QtWidgets.QPushButton(self.mainWindowFrame)
        self.microphoneButton.setGeometry(QtCore.QRect(265, 70, 70, 70))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setUnderline(False)
        self.microphoneButton.setFont(font)
        self.microphoneButton.setStyleSheet("background-color: rgb(244, 249, 250);\n"
"border: none;\n"
"color: black;")
        self.microphoneButton.setText("")
        icon1 = QtGui.QIcon()
        icon1.addPixmap(QtGui.QPixmap("guiPages/../images/microphoneOff.jpg"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.microphoneButton.setIcon(icon1)
        self.microphoneButton.setIconSize(QtCore.QSize(120, 120))
        self.microphoneButton.setObjectName("microphoneButton")
        self.logoButton = QtWidgets.QPushButton(self.mainWindowFrame)
        self.logoButton.setGeometry(QtCore.QRect(500, 10, 70, 70))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setUnderline(False)
        self.logoButton.setFont(font)
        self.logoButton.setStyleSheet("background-color: rgb(244, 249, 250);\n"
"border: none;\n"
"color: black;")
        self.logoButton.setText("")
        icon2 = QtGui.QIcon()
        icon2.addPixmap(QtGui.QPixmap("guiPages/../images/icon_whiteBackground.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.logoButton.setIcon(icon2)
        self.logoButton.setIconSize(QtCore.QSize(70, 70))
        self.logoButton.setObjectName("logoButton")
        self.gClave = QtWidgets.QLabel(self.mainWindowFrame)
        self.gClave.setGeometry(QtCore.QRect(50, 232, 50, 95))
        self.gClave.setText("")
        self.gClave.setPixmap(QtGui.QPixmap("guiPages/../images/gClave.jpg"))
        self.gClave.setScaledContents(True)
        self.gClave.setObjectName("gClave")
        self.clearSheetButton = QtWidgets.QPushButton(self.mainWindowFrame)
        self.clearSheetButton.setGeometry(QtCore.QRect(470, 210, 80, 20))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(13)
        font.setBold(False)
        font.setItalic(False)
        font.setUnderline(True)
        self.clearSheetButton.setFont(font)
        self.clearSheetButton.setAutoFillBackground(False)
        self.clearSheetButton.setStyleSheet("background-color: rgb(244, 249, 250);\n"
"border: none;\n"
"color: black;\n"
"font: 13pt \"Arial\";\n"
"")
        self.clearSheetButton.setIconSize(QtCore.QSize(25, 25))
        self.clearSheetButton.setObjectName("clearSheetButton")
        self.exportButton = QtWidgets.QPushButton(self.mainWindowFrame)
        self.exportButton.setGeometry(QtCore.QRect(450, 330, 100, 30))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(13)
        font.setBold(False)
        font.setItalic(False)
        font.setUnderline(False)
        self.exportButton.setFont(font)
        self.exportButton.setAutoFillBackground(False)
        self.exportButton.setStyleSheet("font: 13pt \"Arial\";\n"
"border: none;\n"
"color: black;\n"
"background-color: rgb(115, 203, 177);")
        self.exportButton.setIconSize(QtCore.QSize(25, 25))
        self.exportButton.setObjectName("exportButton")

        self.gClave_2 = QtWidgets.QLabel(self.mainWindowFrame)
        self.gClave_2.setGeometry(QtCore.QRect(90, 215, 70, 137))
        self.gClave_2.setText("")
        self.gClave_2.setPixmap(QtGui.QPixmap("guiPages/../images/seminima.png"))
        self.gClave_2.setScaledContents(True)
        self.gClave_2.setObjectName("gClave_2")
        self.gClave_2.raise_()
        self.gClave.raise_()

        self.defenitionsButton.raise_()
        self.recordingLabel.raise_()
        self.line4.raise_()
        self.line3.raise_()
        self.line2.raise_()
        self.line1.raise_()
        self.line5.raise_()
        self.microphoneButton.raise_()
        self.logoButton.raise_()
        self.clearSheetButton.raise_()
        self.exportButton.raise_()
        mainWindow.setCentralWidget(self.centralwidget)

        self.retranslateUi(mainWindow)
        QtCore.QMetaObject.connectSlotsByName(mainWindow)

    def retranslateUi(self, mainWindow):
        _translate = QtCore.QCoreApplication.translate
        mainWindow.setWindowTitle(_translate("mainWindow", "MainWindow"))
        self.recordingLabel.setText(_translate("mainWindow", "Not recording"))
        self.clearSheetButton.setText(_translate("mainWindow", "Clear Sheet"))
        self.exportButton.setText(_translate("mainWindow", "Export Sheet"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    mainWindow = QtWidgets.QMainWindow()
    ui = Ui_mainWindow()
    ui.setupUi(mainWindow)
    mainWindow.show()
    sys.exit(app.exec_())
